config/routes.rb
Rails.application.routes.draw do
  root 'trades#index'
  resources :trades, only: %i[index new create show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trade

  validates :name, :base_experience, :trade_group, presence: true

  scope :from_group_a, -> { where(trade_group: 1) }
  scope :from_group_b, -> { where(trade_group: 2) }
end

app/models/trade.rb
class Trade < ApplicationRecord
  has_many :pokemons, dependent: :destroy, inverse_of: :trade
  accepts_nested_attributes_for :pokemons, allow_destroy: true, reject_if: :all_blank

  validates :base_experience_difference, presence: true
  validate :must_have_at_least_one_pokemon_on_each_side_of_the_trade, :max_6_pokemons_on_each_side

  def must_have_at_least_one_pokemon_on_each_side_of_the_trade
    errors.add(:pokemons, 'must have at least one pokemon on each side of the trade') unless
    pokemons_from_group_a.size.positive? &&
    pokemons_from_group_b.size.positive?
  end

  def max_6_pokemons_on_each_side
    errors.add(:pokemons, 'must have maximum 6 pokemons on each side of the trade') unless
    pokemons.size.zero? ||
    pokemons_from_group_a.size < 7 &&
    pokemons_from_group_b.size < 7
  end

  def pokemons_from_group_a
    pokemons.select { |p| p.trade_group == 1 }
  end

  def pokemons_from_group_b
    pokemons.select { |p| p.trade_group == 2 }
  end

  def group_a_experience
    pokemons_from_group_a.reduce(0) { |sum, p| sum + p.base_experience }
  end

  def group_b_experience
    pokemons_from_group_b.reduce(0) { |sum, p| sum + p.base_experience }
  end

  def fair?
    base_experience_difference <= 30
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: %i[ show ]

  # GET /trades or /trades.json
  def index
    # @trades = Trade.includes(:pokemons)
    @pagy, @trades = pagy(Trade.includes(:pokemons).order(created_at: :desc))
  end

  # GET /trades/1 or /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
    6.times { @trade.pokemons.build }
  end

  # POST /trades or /trades.json
  def create
    @trade = Trade.new(trade_params)
    response = PokemonService.new(@trade).call
    @trade = response.payload

    respond_to do |format|
      if response.success? && @trade.save
        format.html { redirect_to @trade, notice: "Trade was successfully created." }
        format.json { render :show, status: :created, location: @trade }
      else
        6.times { @trade.pokemons.build }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trade
    @trade = Trade.includes(:pokemons).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def trade_params
    params.require(:trade).permit(:base_experience_difference, pokemons_attributes: %i[id name trade_group])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
  def link_to_add_fields(name, form, association, partial)
    # Takes an object (@person) and creates a new instance of its associated model (:addresses)
    # To better understand, run the following in your terminal:
    # rails c --sandbox
    # @person = Person.new
    # new_object = @person.send(:addresses).klass.new
    new_object = form.object.send(association).klass.new

    # Saves the unique ID of the object into a variable.
    # This is needed to ensure the key of the associated array is unique. This is makes parsing the content in the `data-fields` attribute easier through Javascript.
    # We could use another method to achive this.
    id = new_object.object_id

    # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block)
    # record_name = :addresses
    # record_object = new_object
    # fields_options = { child_index: id }
    # child_index` is used to ensure the key of the associated array is unique, and that it matched the value in the `data-id` attribute.
    # `person[addresses_attributes][child_index_value][_destroy]`
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      # `association.to_s.singularize + "_fields"` ends up evaluating to `address_fields`
      # The render function will then look for `views/people/_address_fields.html.erb`
      # The render function also needs to be passed the value of 'builder', because `views/people/_address_fields.html.erb` needs this to render the form tags.
      render(partial, f: builder)
    end

    # This renders a simple link, but passes information into `data` attributes.
    # This info can be named anything we want, but in this case we chose `data-id:` and `data-fields:`.
    # The `id:` is from `new_object.object_id`.
    # The `fields:` are rendered from the `fields` blocks.
    # We use `gsub("\n", "")` to remove anywhite space from the rendered partial.
    # The `id:` value needs to match the value used in `child_index: id`.
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "") })
  end

  def icon(icon, options = {})
    file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] += " " + options[:class]
    end
    if options[:width].present?
      svg['width'] = " " + options[:width]
    end
    if options[:height].present?
      svg['height'] = " " + options[:height]
    end
      doc.to_html.html_safe
  end

end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeTrader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar sticky-top navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <%= image_tag('pokeball.png', size: "20x20") %>
          Poke Trader
        </a>
      </div>
    </nav>

  </head>

  <body class="bg-secondary">
    

    <div class="row mt-4">
      <div class="col-8 offset-2">
        <div class="card">
          <div class="card-body mx-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pokemons/_pokemon_a_fields.html.erb
<div class="row nested-fields">
    <%= f.hidden_field :_destroy %>
    <%= f.hidden_field :trade_group, value: 1 %>
    <div class="col-12 mb-3">
        <%= f.text_field :name %>
    </div>
</div>

app/views/pokemons/_pokemon_b_fields.html.erb
<div class="row nested-fields">
    <%= f.hidden_field :_destroy %>
    <%= f.hidden_field :trade_group, value: 2 %>
    <div class="col-12 mb-3">
        <%= f.text_field :name %>
    </div>
</div>

app/views/trades/_form.html.erb
<%= form_with(model: trade) do |form| %>
  <% if trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
        <% trade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row text-center">
    <fieldset class="col-md-5 col-sm-12">
      <legend>Group A:</legend>
      <%= form.fields_for :pokemons do |f| %>
        <%= render partial: 'pokemons/pokemon_a_fields', locals: {f: f} %>
      <% end %>
    </fieldset>
    <div class="col-md-2 col-sm-12 d-flex justify-content-center align-items-center">
      <%= icon("arrow-left-right", width: '40', height: '40') %>
    </div>
    <fieldset class="col-md-5 col-sm-12">
      <legend>Group B:</legend>
      <%= form.fields_for :pokemons do |f| %>
        <%= render partial: 'pokemons/pokemon_b_fields', locals: {f: f} %>
      <% end %>
    </fieldset>
  </div>

  <div class="actions d-flex justify-content-center align-items-center">
    <%= link_to 'Back', trades_path, class: 'btn btn-secondary mx-2' %>
    <%= form.submit 'Create Trade', class: 'btn btn-primary mx-2' %>
  </div>
<% end %>

app/views/trades/_pokemon_fields.html.erb
<div class="nested-fields">
    <%= f.hidden_field :_destroy %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :trade_group %>
        <%= f.text_field :trade_group %>
    </div>
    <div>
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/trades/edit.html.erb
<h1>Editing Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row d-flex justify-content-between align-items-center mb-3">
  <h1>Trades</h1>
  <span class="mx-2">
    <%= link_to 'New Trade', new_trade_path, class: 'btn btn-primary btn-sm' %>
  </span>
</div>
<div class="row text-center mb-3">
<ul class="list-group col-12">
  <% @trades.each do |trade| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-5">
          <div class="row justify-content-center mb-3">
            <% trade.pokemons_from_group_a.each do |pokemon| %>
              <div class="col-md-6 col-lg-4">
              <%= image_tag(pokemon.image_url || 'pokeball.png', size: "80x80", class: "img-thumbnail", alt: pokemon.name) %>
              <div class="caption center-block"><%= pokemon.name %></div>
              </div>
            <% end %>
          </div>
          <div class="row justify-content-center">
            <h5>Group experience <span class="badge bg-info"><%= trade.group_a_experience %></span></h5>
          </div>
        </div>
        <div class="col-2 d-flex align-items-center justify-content-center flex-column">
          <% if trade.fair? %>
            <%= icon("hand-thumbs-up-fill", class: "text-success mb-2", width: '40', height: '40') %>
            Fair
          <% else %>
            <%= icon("hand-thumbs-down-fill", class: "text-danger mb-2", width: '40', height: '40') %>
            Unfair
          <% end %>
        </div>
        <div class="col-5">
          <div class="row justify-content-center mb-3">
            <% trade.pokemons_from_group_b.each do |pokemon| %>
              <div class="col-md-6 col-lg-4">
              <%= image_tag(pokemon.image_url || 'pokeball.png', size: "80x80", class: "img-thumbnail", alt: pokemon.name) %>
              <div class="caption center-block"><%= pokemon.name %></div>
              </div>
            <% end %>
          </div>
          <div class="row justify-content-center">
            <h5>Group experience <span class="badge bg-info"><%= trade.group_b_experience %></span></h5>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>
</div>
<div class="row d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

<br>

app/views/trades/new.html.erb
<div class="d-flex justify-content-start align-items-center mb-3">
  <h1>New Trade</h1>
</div>

<%= render 'form', trade: @trade %>

app/views/trades/show.html.erb
<div class="row mb-3">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Back', trades_path, class: 'btn btn-primary mx-2' %>
</div>
<div class="row">
<div class="col-12 text-center">
  <div class="row">
    <div class="col-5">
      <div class="row justify-content-center mb-3">
        <% @trade.pokemons_from_group_a.each do |pokemon| %>
          <div class="col-12">
          <%= image_tag(pokemon.image_url || 'pokeball.png', size: "80x80", class: "img-thumbnail", alt: pokemon.name) %>
          <div class="caption center-block"><%= pokemon.name %><span class="badge bg-light mx-2"><%= pokemon.base_experience %></span></div>
          </div>
        <% end %>
      </div>
      <div class="row justify-content-center">
        <h6>Total group experience <span class="badge bg-info"><%= @trade.group_a_experience %></span></h6>
      </div>
    </div>
    <div class="col-2 d-flex align-items-center justify-content-center flex-column">
      <% if @trade.fair? %>
        <%= icon("hand-thumbs-up-fill", class: "text-success mb-2", width: '40', height: '40') %>
        Fair
      <% else %>
        <%= icon("hand-thumbs-down-fill", class: "text-danger mb-2", width: '40', height: '40') %>
        Unfair
      <% end %>
    </div>
    <div class="col-5">
      <div class="row justify-content-center mb-3">
        <% @trade.pokemons_from_group_b.each do |pokemon| %>
          <div class="col-12">
          <%= image_tag(pokemon.image_url || 'pokeball.png', size: "80x80", class: "img-thumbnail", alt: pokemon.name) %>
          <div class="caption center-block"><%= pokemon.name %><span class="badge bg-light mx-2"><%= pokemon.base_experience %></span></div>
          </div>
        <% end %>
      </div>
      <div class="row justify-content-center">
        <h6>Total group experience <span class="badge bg-info"><%= @trade.group_b_experience %></span></h6>
      </div>
    </div>
  </div>
</div>
</div>